package com.sanin.tv.media
import android.os.Bundle
import android.text.InputFilter.LengthFilter
import android.view.Gravity
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.ArrayAdapter
import androidx.core.view.updateLayoutParams
import androidx.fragment.app.activityViewModels
import androidx.lifecycle.lifecycleScope
import com.sanin.tv.BottomSheetDialogFragment
import com.sanin.tv.DatePickerFragment
import com.sanin.tv.InputFilterMinMax
import com.sanin.tv.R
import com.sanin.tv.Refresh
import com.sanin.tv.connections.PendingProgressUpdate
import com.sanin.tv.connections.anilist.Anilist
import com.sanin.tv.connections.anilist.api.FuzzyDate
import com.sanin.tv.connections.mal.MAL
import com.sanin.tv.databinding.BottomSheetMediaListBinding
import com.sanin.tv.navBarHeight
import com.sanin.tv.settings.saving.PrefManager
import com.sanin.tv.settings.saving.PrefName
import com.sanin.tv.snackString
import com.sanin.tv.tryWith
import com.google.android.material.materialswitch.MaterialSwitch
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
